# set the build number
name: $(Year:yyyy).$(Month).$(DayOfMonth).$(BuildID)

on:
  push:
    branches: [ "main","staging","develop" ]
  pull_request:
    branches: [ "main","staging","develop" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest  
    env:
      Solution_Name: identity.sln                      

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore
      working-directory: IdentityPackage

    - name: build
      run: dotnet build --configuration Release --no-restore -p:PackageVersion=$(BUILD_TIMESTAMP) 
      working-directory: IdentityPackage

    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with:   
       PROJECT_FILE_PATH: IdentityPackage/IdentityPackage.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
