# set the build number
name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest  
    env:
      Solution_Name: identity.sln                      
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore
      working-directory: IdentityPackage

    - name: build
      run: dotnet build --configuration Release --no-restore -p:PackageVersion='${{ env.BUILD_NUMBER }}'
      working-directory: IdentityPackage

    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.5  
      with:   
       PROJECT_FILE_PATH: IdentityPackage/IdentityPackage.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
       PACKAGE_NAME: Core
       VERSION_STATIC: 1.0.${{ env.BUILD_NUMBER }}
